pull_request_rules:
  - name: Merge PRs that are ready
    conditions:
      #- status-success=Travis CI - Pull Request
      - "#approved-reviews-by>=2"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - label!="work-in-progress"
    actions:
      merge:
        strict: true
        strict_method: rebase
        method: squash

  - name: Delete the PR branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}

  - name: auto add wip
    conditions:
      # match a few flavours of wip
      - title~=^(\[wip\]( |:) |\[WIP\]( |:) |wip( |:) |WIP( |:)).*
    actions:
      label:
        add: ["work-in-progress"]
